### ISSUE TITLE
When someone dislike a post usersWhoLike gets empty (FIXED)

### ISSUE THREAD

**Issue by vinibpereira** [jmsanchezdiaz/blog-personal#1]
Hello Juan, I've notice a issue in the project, when someone dislike a post the usersWhoLike gets empty.

eg: 5 uses liked the post when someone dislike the post it gets empty (0 likes)

By the way congrats for the project **I'm learning new concepts about firebase 9 / hooks with it. Thank you**. Cheers from Brazil

**Comment by jmsanchezdiaz** [comment]
Hi vini!
Thank you so much for the feedback i'll fix it as soon as possible.
Greetings!
